language: python

matrix:
  include:
    - python: "2.7"

install:
  - pip install coveralls
  - pip install bandit
  - pip install .
  - pip install -r test-requirements.txt

script:
  - coverage run --source repokid -m py.test
  - bandit -r . -ll -ii -x repokid/tests/

after_success:
  - coveralls

notifications:
  email:
    tmcpeak@netflix.com
    pkelley@netflix.com
